### ISSUE TITLE
progressMonitorFunction slow to interrupt filter

### ISSUE THREAD

**Issue by fluidray** [RenderKit/oidn#240]
In recent versions of OIDN and using the CPU device, returning false from the progress monitor function takes a while to interrupt the filter. I noticed that the problem is more pronounced when executing the filter with cleanAux=true and high quality mode, but it also present when pre filtering the albedo and normal buffers.
For real-time editing applications it would be necessary to interrupt the filter quickly to keep interactivity.

**Comment by atafra** [comment]
Unfortunately this isn't enough information to debug this issue. I did a quick check but I don't see anything unusual. Denoising should immediately stop after returning `false` in the progress callback because an error is thrown at that point. The behavior shouldn't be any different from older versions, and shouldn't depend at all on cleanAux or pre-filtering.

Could you please be more specific? E.g. which is the first OIDN version that has this issue, what exactly do you mean by "slow", etc. But a small reproducer would be best.

**Comment by atafra** [comment]
Sorry, I was wrong. I could reproduce the issue. The delay is indeed much worse than it should be. I'm looking into it. You don't need to provide more details or a reproducer anymore.

**Comment by atafra** [comment]
The issue is now fixed in `devel` and will be released soon in `v2.3.1`. Thanks for reporting this issue! Please let me know whether you still encounter any issues.

**Comment by nicolacandussi** [comment]
That's great! Thanks for the quick fix!

**Comment by fluidray** [comment]
That's great! Thanks for the quick fix!

**Comment by fluidray** [comment]
Just tested, everything works fine. Thanks again!

**Comment by atafra** [comment]
I'm happy to hear, thanks for the feedback!
