### ISSUE TITLE
Clarification on prefiltering normal in denoising example

### ISSUE THREAD

**Issue by hchoi405** [RenderKit/oidn#241]
Hi contributors,

I've been going through the README to understand how to denoise an HDR image along with noisy auxiliary buffers. However, I’m a bit confused about the example in the document titled "Denoising with Prefiltering (C++11 API)". Specifically, the example seems to perform an additional denoising pass on both the albedo and normal buffers, treating them as a single beauty image.

Denoising the albedo seems fine since it's typically in the range [0, 1]. However, the normal buffer, which has values in the range [-1, 1], gets clamped to [0, 1] after denoising. This clamping discards useful information in the [-1, 0) range. 
According to the documentation, the denoiser is trained with normal buffers in the [-1, 1] range, but the example appears to use the clamped normal buffer in the [0, 1] range.

Could you clarify if this is the intended way to prefilter the auxiliary buffers, or am I missing something?

Thank you for reading.

**Comment by atafra** [comment]
In the provided example code, the albedo and normal buffers are **not** denoised as beauty images because these are specified as `"albedo"` and `"normal"` instead of `"color"`. This means that OIDN knows the correct range of the auxiliary features and won't be clamped incorrectly. In addition to correct clamping, OIDN also uses completely different denoising weights for albedo and normal for optimal results.

**Comment by hchoi405** [comment]
Thank you for your quick response and clarification! I mistakenly thought they were treated as standard beauty images.
